version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
    volumes: 
      - "sqldata:/var/opt/mssql"

  redis:
    image: redis:7-alpine
    ports: 
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: 
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

volumes:
  sqldata:
