-- Core Tables Migration

-- Users --
CREATE TABLE Users (
    Id              UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email           NVARCHAR(255) NOT NULL UNIQUE,
    Name            NVARCHAR(255) NOT NULL,
    AvatarUrl       NVARCHAR(500) NULL,
    PasswordHash    NVARCHAR(255) NULL,
    IsEmailVerified BIT NOT NULL DEFAULT 0,
    MfaEnabled      BIT NOT NULL DEFAULT 0,
    MfaSecret       NVARCHAR(255) NULL,
    CreatedAt       DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt       DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    DeletedAt       DATETIME2 NULL
);

-- Workspaces --
CREATE TABLE Workspaces (
    Id        UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name      NVARCHAR(255) NOT NULL,
    Slug      NVARCHAR(100) NOT NULL UNIQUE,
    AvatarUrl NVARCHAR(500) NULL,
    OwnerId   UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE WorkspaceMembers (
    Id          UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    WorkspaceId UNIQUEIDENTIFIER NOT NULL REFERENCES Workspaces(Id),
    UserId      UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
    Role        NVARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    JoinedAt    DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT UQ_WorkspaceMember UNIQUE (WorkspaceId, UserId)
);

-- Projects --
CREATE TABLE Projects (
    Id          UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    WorkspaceId UNIQUEIDENTIFIER NOT NULL REFERENCES Workspaces(Id),
    Name        NVARCHAR(255) NOT NULL,
    [Key]       NVARCHAR(20) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    AvatarUrl   NVARCHAR(500) NULL,
    Type        NVARCHAR(20) NOT NULL DEFAULT 'SCRUM',
    Status      NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CreatedById UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
    StartDate   DATE NULL,
    EndDate     DATE NULL,
    CreatedAt   DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt   DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT UQ_ProjectKey UNIQUE (WorkspaceId, [Key])
);

-- Sprints --
CREATE TABLE Sprints (
    Id          UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProjectId   UNIQUEIDENTIFIER NOT NULL REFERENCES Projects(Id),
    Name        NVARCHAR(255) NOT NULL,
    Goal        NVARCHAR(MAX) NULL,
    Status      NVARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    StartDate   DATETIME2 NULL,
    EndDate     DATETIME2 NULL,
    CompletedAt DATETIME2 NULL,
    CreatedAt   DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt   DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

-- Tasks (Issues) --
CREATE TABLE Tasks (
    Id           UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProjectId    UNIQUEIDENTIFIER NOT NULL REFERENCES Projects(Id),
    WorkspaceId  UNIQUEIDENTIFIER NOT NULL REFERENCES Workspaces(Id),
    IssueKey     NVARCHAR(30) NOT NULL,
    Title        NVARCHAR(500) NOT NULL,
    Description  NVARCHAR(MAX) NULL,
    Type         NVARCHAR(20) NOT NULL DEFAULT 'TASK',
    Status       NVARCHAR(100) NOT NULL,
    Priority     NVARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    ReporterId   UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
    SprintId     UNIQUEIDENTIFIER NULL REFERENCES Sprints(Id),
    EpicId       UNIQUEIDENTIFIER NULL REFERENCES Tasks(Id),
    ParentTaskId UNIQUEIDENTIFIER NULL REFERENCES Tasks(Id),
    StoryPoints  FLOAT NULL,
    StartDate    DATE NULL,
    DueDate      DATE NULL,
    Position     FLOAT NOT NULL DEFAULT 0,
    CreatedAt    DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt    DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    ResolvedAt   DATETIME2 NULL,
    DeletedAt    DATETIME2 NULL,
    CONSTRAINT UQ_IssueKey UNIQUE (ProjectId, IssueKey)
);

CREATE TABLE TaskAssignees (
    TaskId UNIQUEIDENTIFIER NOT NULL REFERENCES Tasks(Id),
    UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
    PRIMARY KEY (TaskId, UserId)
);

CREATE TABLE TaskLabels (
    TaskId UNIQUEIDENTIFIER NOT NULL REFERENCES Tasks(Id),
    Label  NVARCHAR(100) NOT NULL,
    PRIMARY KEY (TaskId, Label)
);
