-- Create ProjectFlow Database
-- This script should be run by a user with CREATE DATABASE permissions

USE master;
GO

-- Drop existing database if needed (BE CAREFUL IN PRODUCTION!)
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'ProjectFlow')
BEGIN
    ALTER DATABASE [ProjectFlow] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [ProjectFlow];
END
GO

-- Create new database
CREATE DATABASE [ProjectFlow]
    ON PRIMARY (
        NAME = N'ProjectFlow',
        FILENAME = N'/var/opt/mssql/data/ProjectFlow.mdf',
        SIZE = 100MB,
        MAXSIZE = UNLIMITED,
        FILEGROWTH = 10MB
    )
    LOG ON (
        NAME = N'ProjectFlow_log',
        FILENAME = N'/var/opt/mssql/data/ProjectFlow_log.ldf',
        SIZE = 50MB,
        MAXSIZE = UNLIMITED,
        FILEGROWTH = 10MB
    );
GO

-- Set database options
ALTER DATABASE [ProjectFlow] SET COMPATIBILITY_LEVEL = 160; -- SQL Server 2022
ALTER DATABASE [ProjectFlow] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [ProjectFlow] SET ANSI_NULLS OFF;
ALTER DATABASE [ProjectFlow] SET ANSI_PADDING OFF;
ALTER DATABASE [ProjectFlow] SET ANSI_WARNINGS OFF;
ALTER DATABASE [ProjectFlow] SET ARITHABORT OFF;
ALTER DATABASE [ProjectFlow] SET AUTO_CLOSE OFF;
ALTER DATABASE [ProjectFlow] SET AUTO_SHRINK OFF;
ALTER DATABASE [ProjectFlow] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [ProjectFlow] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [ProjectFlow] SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE [ProjectFlow] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [ProjectFlow] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [ProjectFlow] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [ProjectFlow] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [ProjectFlow] SET DISABLE_BROKER;
ALTER DATABASE [ProjectFlow] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [ProjectFlow] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [ProjectFlow] SET TRUSTWORTHY OFF;
ALTER DATABASE [ProjectFlow] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [ProjectFlow] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [ProjectFlow] SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE [ProjectFlow] SET RECOVERY FULL;
ALTER DATABASE [ProjectFlow] SET MULTI_USER;
ALTER DATABASE [ProjectFlow] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [ProjectFlow] SET DB_CHAINING OFF;
ALTER DATABASE [ProjectFlow] SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF);
ALTER DATABASE [ProjectFlow] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [ProjectFlow] SET DELAYED_DURABILITY = DISABLED;
GO

USE [ProjectFlow];
GO

-- Create migration history table
CREATE TABLE MigrationHistory (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MigrationName NVARCHAR(255) NOT NULL,
    AppliedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO

-- Insert initial migration
INSERT INTO MigrationHistory (MigrationName) VALUES ('0000_create_database.sql');
GO

PRINT 'Database ProjectFlow created successfully';
GO