CREATE OR ALTER PROCEDURE dbo.usp_Tag_Delete
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM dbo.TaskLabelLinks WHERE LabelId = @Id;
        DELETE FROM dbo.Labels WHERE Id = @Id;
        COMMIT TRANSACTION;
    END TRY BEGIN CATCH IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION; THROW; END CATCH
END;
