CREATE OR ALTER PROCEDURE dbo.usp_Tag_UnlinkTask
    @TaskId UNIQUEIDENTIFIER, @TagId UNIQUEIDENTIFIER
AS
BEGIN SET NOCOUNT ON; DELETE FROM dbo.TaskLabelLinks WHERE TaskId = @TaskId AND LabelId = @TagId; END;
