CREATE OR ALTER PROCEDURE dbo.usp_TaskWatcher_Remove @TaskId UNIQUEIDENTIFIER, @UserId UNIQUEIDENTIFIER
AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.TaskWatchers WHERE TaskId = @TaskId AND UserId = @UserId; END;
