CREATE OR ALTER PROCEDURE dbo.usp_Dashboard_Delete
  @Id UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE dbo.Dashboards SET DeletedAt = SYSUTCDATETIME(), UpdatedAt = SYSUTCDATETIME()
   WHERE Id = @Id AND DeletedAt IS NULL;
  SELECT * FROM dbo.Dashboards WHERE Id = @Id;
END;
GO
